<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Azure.AI.Inference" Version="13.1.1-preview.1.26105.8" />
    <PackageVersion Include="Aspire.Azure.AI.OpenAI" Version="13.1.1-preview.1.26105.8" />
    <PackageVersion Include="Aspire.Hosting.Azure.AIFoundry" Version="13.1.1-preview.1.26105.8" />
    <PackageVersion Include="Aspire.Hosting.Azure.CognitiveServices" Version="13.1.1" />
    <PackageVersion Include="Aspire.Hosting.GitHub.Models" Version="13.1.1" />
    <PackageVersion Include="Azure.AI.OpenAI" Version="2.8.0-beta.1" />
    <PackageVersion Include="CommunityToolkit.Aspire.Hosting.Ollama" Version="13.1.1" />
    <PackageVersion Include="CommunityToolkit.Aspire.OllamaSharp" Version="13.1.1" />
    <PackageVersion Include="Microsoft.Agents.AI" Version="1.0.0-preview.260212.1" />
    <PackageVersion Include="Microsoft.Agents.AI.DevUI" Version="1.0.0-preview.260212.1" />
    <PackageVersion Include="Microsoft.Agents.AI.Hosting" Version="1.0.0-preview.260212.1" />
    <PackageVersion Include="Microsoft.Agents.AI.Hosting.OpenAI" Version="1.0.0-alpha.260212.1" />
    <PackageVersion Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-preview.260212.1" />
    <PackageVersion Include="Microsoft.Agents.AI.Workflows" Version="1.0.0-preview.260212.1" />
    <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.3.0" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.3.0" />
    <PackageVersion Include="Neo4j.Driver" Version="6.0.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.0" />
    <PackageVersion Include="PdfPig" Version="0.1.14-alpha-20260216-7e370" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.19.0.132793" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
</Project>